name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout DemoLibrary
      uses: actions/checkout@v4
      
    - name: Use Node v22
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Install Dependencies    
      run: npm ci

    - name: Instal Playwright 
      run: npx playwright install  
 
    - name: Update the config
      run: echo "export const settings = { host:"http://localhost:3030"}" > src/config.js

    - name: Run Front End
      run: npm start &

    - name: Run Back End
      run: npm run server &
    
    - name: Run Tests 
      run: npm test

  deploy-be:
   runs-on: ubuntu-latest

   needs: build_test

   steps:
    - name: Deploy Backend
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
          service_id: ${{ secrets.RENDER_SERVICE_BE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true 

  deploy-fe:
   runs-on: ubuntu-latest

   needs: build_test

   steps:
    - name: Deploy Frondend
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
          service_id: ${{ secrets.RENDER_SERVICE_FE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true 