name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout DemoLibrary
      uses: actions/checkout@v4
      
    - name: Use Node v22
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Install Dependencies    
      run: npm ci

    - name: Run Front End
      run: npm start &

    - name: Run Back End
      run: npm run server &

    - name: Download Wait-for-it
      run: |
        curl -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
        chmod +x wait-for-it.sh

    - name: Wait for Front End
      run: ./wait-for-it.sh localhost:3000 -t 30

    - name: Wait for Back End
      run: ./wait-for-it.sh localhost:3030 -t 30
    
    - name: Run Tests 
      run: npm test
